name: tabl
description: "TabL"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-dev.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.4 # Add direct dependency
  local_auth: ^2.1.7
  local_auth_android: ^1.0.36 # Add direct dependency
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/static-splash.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#025f57"
  image: assets/images/static-splash.png
  android: true
  ios: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/images/
